name: third action

on:
  workflow_dispatch:
    inputs: ## aparece cuando le das a run workflow en github
      debug_mode:
        type: boolean ## casilla para seleccionar
        description: Debug
        default: false
        required: false
      sample_value:
        type: string ## caja para escribir
        description: cualquier valor
        default: "" 
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest 
    steps:
      - name: first step
        run: echo "Hello"
      - name: second step
        run: echo "there"
  say_back:
    runs-on: ubuntu-latest
    needs: say_hello
    steps:
      - name: first step
        run: echo "Hello"
      - name: second step
        run: echo ${{ github.event.inputs.debug_mode }}

